root: ./

​structure:
  readme: README.md
  summary: SUMMARY.md​

redirects:
  page1: ./page1.md
  page1-1: ./page1-1.md
  page1-2: ./page1-2.md
  page2: ./page2.md
  page2-1: ./page2-1.md
  page2-2: ./page2-2.md
  another-page: ./another-page.md
